2022-10-02
deno-ja/denobata-monthly-report pull request #33
Opened 2022-10-02 15:47 UTC by windchime-yk

2022-10-08 03:44 UTC, windchime-yk commented
@kt3k @uki00a 
レビュー遅れてしまってすみません！ ご確認お願いします！ 🙇 
時間が経ってしまっているので、uki00aさんにもレビュー依頼させていただきました。

また、deno-jaにAdmin権限で入っていない関係でDeno Deployにデプロイできなくなっているみたいでして、Admin権限付与していただくか、deno-jaのDeno Deployプロジェクトにあげていただくことは可能でしょうか？

2022-10-08 03:48 UTC, windchime-yk reviewed
個人的に気になっている点を書かせていただきました 🙇

2022-10-08 03:48 UTC, windchime-yk commented on docs/report/13.md
> +- 新しいパーミッションができたのは2年ぶり（ここが微妙に違う気がする）
書いている途中に気になったのはここの○年ぶりというのが合っているかどうか、です。
確か○ヶ月ぶり……みたいな話でされてたような気がしており。
大筋で問題なければ、そのまま入れてしまいます。

2022-10-08 03:48 UTC, windchime-yk commented on docs/report/13.md
> +- Softwere Designに連載する話
全体の中で誤記がないか軽く確認していただきたいのと同時に、公開可能な情報かも確認いただきたいです。
連載の話など、もしまだダメそうであれば削除いたします。

2022-10-08 04:45 UTC, uki00a requested changes
レポートの件、ありがとうございます！

細かい箇所で2点だけコメントしましたが、それ以外は全体的によさそうに見えます :ok_man: :bowing_man:

2022-10-08 04:45 UTC, uki00a commented on docs/report/13.md
> +  - yarn readyみたいな感じでバーチャルなものが作られる
多分、ここはyarn berryな気がします！
```suggestion
  - yarn berryみたいな感じでバーチャルなものが作られる
```

2022-10-08 04:45 UTC, uki00a commented on docs/report/13.md
> +  - そのレイヤーをRustのCのレイヤーを渡して高速化していた
正直私もうろ覚えなのですが、たしか、↓のような内容だった気がします :thinking:
```suggestion
  - そのレイヤーをRustからCのコードを動的に生成し、tinyccでコンパイルすることで高速化していた
```

2022-10-08 14:46 UTC, windchime-yk commented on docs/report/13.md
> +  - yarn readyみたいな感じでバーチャルなものが作られる
ご指摘ありがとうございます！ 修正します！

2022-10-08 14:47 UTC, windchime-yk commented on docs/report/13.md
> +  - そのレイヤーをRustのCのレイヤーを渡して高速化していた
なるほどなるほど……JIT再実装周りちんぷんかんぷんになりながら聞いていたので、ご指摘ありがとうございます！ 🙏 
修正いたします！

2022-10-09 07:46 UTC, uki00a approved these changes
修正ありがとうございます！私の方はLGTMです :bow:

2022-10-09 19:50 UTC, kt3k commented on docs/report/13.md
> +- 新しいパーミッションができたのは2年ぶり（ここが微妙に違う気がする）
3年ぶりが正かと思います

2022-10-09 19:52 UTC, kt3k commented on docs/report/13.md
> +- 本来はService Workerのみらしい
こちら、自分の認識違いで、「Service Workerのみ」では無かったようなので、この行は消してもらえればと思いますmm

2022-10-09 20:02 UTC, kt3k commented on docs/report/13.md
> +  - 今バサーションが142なので最高記録かも
```suggestion
  - コンバセーションが142なので最高記録かも
```

2022-10-09 20:03 UTC, kt3k commented on docs/report/13.md
> +- Divyさんは高校生のはずなんだけど、どこでこれだけの技術を身に着けているのか
```suggestion
- Divyさんは高校生のはずなんだけど、どこでこれだけの技術を身につけているのか
```

2022-10-09 20:07 UTC, kt3k commented on docs/report/13.md
> +  - お互いの期待値が合わなかったといういつもの理由のみ説明があった
このあたり、議事録としては残さなくても良いかなという気がするのですがどうでしょう・・・?

2022-10-09 20:08 UTC, kt3k commented on docs/report/13.md
> +  - 入社するまでDenoに1コントリビュートもしてなかった
このあたりも、若干センシティブな内容だったり憶測を含んだ内容なので、できれば議事録には残さない形のほうが良いかなと思います・・・

2022-10-09 20:10 UTC, kt3k reviewed
一旦見終わりました。毎回議事録のまとめありがとうございます〜mm

2022-10-10 13:08 UTC, windchime-yk commented on docs/report/13.md
> +  - お互いの期待値が合わなかったといういつもの理由のみ説明があった
> 議事録としては残さなくても良いかなという気がする

私としても同意です！ 見落とし失礼しました 🙇

2022-10-10 14:22 UTC, windchime-yk commented
@kt3k 
ご確認ありがとうございます！ 修正しましたので再度ご確認お願いします 🙇 

> 毎回議事録のまとめありがとうございます〜mm

いえいえー！ こちらこそ毎月開催いただきありがとうございますー！
Denoの最新動向や実装の意図、周りの方がDenoでどんなことをしているのか追えて大変有意義な時間を過ごさせていただいております！

権限周りも対応いただきありがとうございました！ 無事にLinkし直すことができました！

2022-10-10 14:22 UTC, windchime-yk commented
@uki00a 
急なレビューのお願いにもかかわらず対応してくださり、ありがとうございます 🙇
いつもスライドにまとめてくださって、わかりやすくて大変助かっております！

2022-10-10 14:29 UTC, kt3k approved these changes
LGTM 👍

2022-10-10 15:09 UTC, merged