2022-11-20
deno-ja/denobata-monthly-report pull request #35
Opened 2022-11-20 03:38 UTC by windchime-yk

2022-11-30 17:26 UTC, windchime-yk commented
@kt3k @uki00a 
大変遅くなってしまいました、すみません 🙇
 
今回、特に確認していただきたい点はございません。
過不足ありましたら、ご指摘いただければ幸いです。

2022-11-30 21:33 UTC, uki00a requested changes
いつもまとめていただき、ありがとうございます！

軽微な内容ですが、数箇所だけコメントいたしました

それ以外は全体的に良さそうに見えます :ok_man:

2022-11-30 21:33 UTC, uki00a commented on docs/report/15.md
> +- ReadableStreamだったら`piped`を使う
軽微ですが、以下のようにすると少し正確になりそうな気がしました。
```suggestion
- `piped`を使うと[Stream API](https://developer.mozilla.org/ja/docs/Web/API/Streams_API)を使ってサブプロセスの標準入出力を制御できる
```

2022-11-30 21:33 UTC, uki00a commented on docs/report/15.md
> +    - メモリ率とか受け取れる
タイポを見つけました。

```suggestion
    - メモリ利用率とか受け取れる
```

2022-12-01 03:47 UTC, windchime-yk commented on docs/report/15.md
> +- ReadableStreamだったら`piped`を使う
ありがとうございます！ 取り入れさせていただきます！ 🙇

2022-12-01 03:48 UTC, windchime-yk commented on docs/report/15.md
> +    - メモリ率とか受け取れる
ご指摘ありがとうございます 🙏

2022-12-01 04:30 UTC, kt3k approved these changes

2022-12-01 16:15 UTC, windchime-yk commented
@uki00a 
いつもレビューありがとうございます！ ご指摘の点修正いたしました！

2022-12-01 20:12 UTC, uki00a approved these changes
LGTM！修正ありがとうございます！ :bow:

2022-12-02 00:25 UTC, merged