2023-03-10
deno-ja/denobata-monthly-report pull request #37
Opened 2023-03-08 16:47 UTC by windchime-yk

2023-03-15 16:35 UTC, windchime-yk commented
@kt3k @uki00a 
遅くなりましたがレポート作成しました！
記憶が定かでないなど、気になる点はTODOコメントで記載しています。
他にも気になる点があれば、ご指摘いただければ幸いです。
ご確認よろしくお願いします！ 🙇

2023-03-15 23:34 UTC, uki00a requested changes
ありがとうございます！

軽微ですが、2点だけコメントいたしましたため、お手すきの際に確認をお願いいただけますでしょうか :bow:

2023-03-15 23:34 UTC, uki00a commented on docs/report/17.md
> +    - C++からラッパー経由で叩いてる
うろ覚えですが、たしか[node-sqlite3](https://github.com/TryGhost/node-sqlite3)は[Node-APIのC++ラッパー](https://github.com/nodejs/node-addon-api)を利用している、というような内容だった気がします

2023-03-15 23:34 UTC, uki00a commented on docs/report/17.md
> +- DenoがSWCをガッツリ使う前は、SWCのmicroがnightlyに依存してた
多分、タイポな気がします :eyes:
```suggestion
- DenoがSWCをガッツリ使う前は、SWCのmacroがnightlyに依存してた
```

2023-03-16 02:34 UTC, kt3k commented on docs/report/17.md
> +    - TypeScriptで実装してたところはRustには及ばないよね<!-- TODO: 文脈が不明 -->
> TODO: 文脈が不明

ちょっと記憶がないので、削除で良いかなと・・・

2023-03-16 02:35 UTC, kt3k commented on docs/report/17.md
> +    - crypto-browserifyは完成されている<!-- TODO: 完成されていると読み取ったが違和感があるので、もし間違っていればご指摘お願いします -->ので、この機能がほしいと引き出せばNode.jsのcryptoになっていたので楽だった
> TODO: 完成されていると読み取ったが違和感があるので、もし間違っていればご指摘お願いします

完成されているであっていると思います。crypto-browserify は出来が良い、ぐらいの意味かと思います

2023-03-16 02:38 UTC, kt3k approved these changes
LGTM

2023-03-16 17:00 UTC, windchime-yk commented on docs/report/17.md
> +    - C++からラッパー経由で叩いてる
ありがとうございますー！ 反映します！

2023-03-16 17:01 UTC, windchime-yk commented on docs/report/17.md
> +    - TypeScriptで実装してたところはRustには及ばないよね<!-- TODO: 文脈が不明 -->
ありがとうございます！ 削除します！

2023-03-16 17:11 UTC, windchime-yk commented on docs/report/17.md
> +    - crypto-browserifyは完成されている<!-- TODO: 完成されていると読み取ったが違和感があるので、もし間違っていればご指摘お願いします -->ので、この機能がほしいと引き出せばNode.jsのcryptoになっていたので楽だった
ありがとうございます！ 記載そのままでコメントだけ消す形にしようと思います！

2023-03-16 17:42 UTC, windchime-yk commented
@kt3k @uki00a 
レビューありがとうございます！
修正しましたので、ご確認お願いしますー！
また、ご指摘や補足がなかったTODOコメントについてはそのまま削除しましたが、もし気になる点ありましたらお教えください！
https://github.com/deno-ja/denobata-monthly-report/pull/37/commits/ac314eef38517b4d5a62a201e400bf6f6a80421c

2023-03-16 21:33 UTC, uki00a approved these changes
ありがとうございます！LGTM!! :+1:

2023-03-19 05:33 UTC, kt3k approved these changes
LGTM 👍

2023-03-19 08:06 UTC, merged