2023-05-12
deno-ja/denobata-monthly-report pull request #40
Opened 2023-05-11 14:55 UTC by windchime-yk

2023-05-15 00:15 UTC, windchime-yk reviewed
@kt3k @uki00a 
気になる点をGitHubコメントで補足いたしました。
他、気になる点などありましたらご指摘いただければ幸いです！

ご確認よろしくお願いします！

2023-05-15 00:30 UTC, uki00a requested changes
まとめていただき、ありがとうございます！

細かい箇所で数点程コメントしたため、お手すきの際に確認をお願いいただけますでしょうか :bow:

それ以外は全体的によさそうに見えます！ :bow:

2023-05-15 00:30 UTC, uki00a commented on docs/report/19.md
> +    - 一番近くにあるDeno KVの同期が遅れている可能性があり、最新じゃない可能性がある
以下については、一つ下のブロックに移すとよさそうに思いました。
```suggestion
```

2023-05-15 00:30 UTC, uki00a commented on docs/report/19.md
> +  - 結果整合はちょっと遅れてもいいから返答をくれという場合
こちらに移すイメージになります :bow:
```suggestion
  - 結果整合はちょっと遅れてもいいから返答をくれという場合
    - 一番近くにあるDeno KVの同期が遅れている可能性があり、最新じゃない可能性がある
```

2023-05-15 00:30 UTC, uki00a commented on docs/report/19.md
> +  - 結果整合でしか情報を登録してすぐに反映するときが使えない
こちはら強整合な気がします！ :eyes:

```suggestion
  - 強整合でしか情報を登録してすぐに反映するときが使えない
```

2023-05-15 00:30 UTC, uki00a commented on docs/report/19.md
> +  - 強整合で2〜3ミリ秒、結果整合で7〜50ミリ秒
おそらく、結果整合と強整合を入れ替えるとよさそうな気がします
```suggestion
  - 結果整合で2〜3ミリ秒、強整合で7〜50ミリ秒
```

2023-05-15 04:34 UTC, kt3k commented on docs/report/19.md
> +  - 強整合で2〜3ミリ秒、結果整合で7〜50ミリ秒
そんなに速くなくて、結果整合 50ms 強整合 220ms ぐらいのようでした
```suggestion
  - 結果整合で50ミリ秒、強整合で220ミリ秒
```

2023-05-15 04:45 UTC, kt3k commented on docs/report/19.md
> +- Cloudflareはインターネットトラフィックの20%を捌いている<!-- TODO: ここの資料がほしい -->ので、世の中でこういう攻撃が起こっているというはだいたいわかるらしい
自分が edge_study という勉強会で見たこの資料だと cloudflare が 20% になっていますが、測り方が色々ありそうなので、一概にインターネットの20%と言い切るのは安全ではないかも知れない気がして来ました・・・(一旦議事録上は載せてもらって大丈夫です〜
https://es23322.pages.dev/#12

2023-05-15 04:46 UTC, kt3k approved these changes
LGTM

2023-05-15 13:17 UTC, windchime-yk commented on docs/report/19.md
> +  - 結果整合でしか情報を登録してすぐに反映するときが使えない
ご指摘ありがとうございます！

2023-05-15 13:18 UTC, windchime-yk commented on docs/report/19.md
> +  - 強整合で2〜3ミリ秒、結果整合で7〜50ミリ秒
ご指摘と値の訂正、ありがとうございます！ 🙏

2023-05-15 13:20 UTC, windchime-yk commented on docs/report/19.md
> +  - 結果整合はちょっと遅れてもいいから返答をくれという場合
ありがとうございます！ 反映させていただきます！

2023-05-15 14:01 UTC, windchime-yk commented
@uki00a @kt3k 
修正しましたので、改めてご確認お願いします！

2023-05-15 19:29 UTC, uki00a approved these changes
LGTM!!

対応ありがとうございます！ :bow:

2023-05-16 04:06 UTC, kt3k approved these changes
LGTM!

2023-05-16 09:42 UTC, merged