2023-06-02
deno-ja/denobata-monthly-report pull request #41
Opened 2023-06-01 15:33 UTC by windchime-yk

2023-06-04 15:56 UTC, windchime-yk reviewed
@kt3k @uki00a 
夜分遅くに失礼いたします 🙇 
第20回のレポートを作成しましたので、レビューをお願いいたします！

気になる点や聞き逃してしまった部分の補足願いなどは、コメントで記載しています。
他、気になる点ございましたら指摘お願いします！

2023-06-04 15:56 UTC, windchime-yk commented on docs/report/20.md
> +  - Google Developer Advocateの人が`setTimeout`などを並べ立てて「ハンドラ関数が第一引数になっているのはデザインの失敗である」とツイートしてた<!--このツイートのリンクが知りたいです-->
Google Developer Advocateの人の当該ツイートリンクが頂きたいです！

個人的に、どうしてデザインの失敗なのかがいまいちわかっていないので、その方のお話が見たいという気持ちもあります。

2023-06-04 15:56 UTC, windchime-yk commented on docs/report/20.md
> +  - deno compileとdeno 〇〇<!-- TODO: ここが聞き取れなかったです -->で`npm:`を使える道が拓ける
deno compileともう一つのコマンドが何か、聞き逃してしまったので教えていただきたいです 🙇

2023-06-04 15:56 UTC, windchime-yk commented on docs/report/20.md
> +    - 〇〇<!-- ここを聞き逃しました -->が同じプロセスに同居しているので、別プロセスが建てられると攻撃に悪用されてしまうため
こちらも聞き逃してしまったので、教えていただきたいです。

2023-06-04 15:56 UTC, windchime-yk commented on docs/report/20.md
> +  - tizelStripe<!-- 聞き取れなかったので教えてほしいです -->もある
サービス名がなんとなく聞き取れたのですが、聞き覚えがなく探しても分からなかったので教えていただけると幸いです。

2023-06-04 15:56 UTC, windchime-yk commented on docs/report/20.md
> +  <!-- TODO: Kintoneの人に尋ねた話、載せないほうが良ければ変えます -->
個別に尋ねれば良かったのですが、この辺り載せないほうが良ければ消そうかと思っています。

2023-06-04 17:21 UTC, uki00a requested changes
ありがとうございます！！全体的によさそうに見えます！

細かな箇所で数点だけコメントしたため、お手すきの際に確認をお願いいただけますでしょうか :bow:

2023-06-04 17:21 UTC, uki00a commented on docs/report/20.md
> +  - deno compileとdeno 〇〇<!-- TODO: ここが聞き取れなかったです -->で`npm:`を使える道が拓ける
ここはたしか`deno lsp`だった気がします！
```suggestion
  - deno compileとdeno lspで`npm:`を使える道が拓ける
```

2023-06-04 17:21 UTC, uki00a commented on docs/report/20.md
> +    - 〇〇<!-- ここを聞き逃しました -->が同じプロセスに同居しているので、別プロセスが建てられると攻撃に悪用されてしまうため
私も正直うろ覚えではありますが、たしか
```suggestion
    - V8のIsolateが同じホストに同居しているので、別プロセスが建てられると攻撃に悪用されてしまうため
```
みたいな内容だった気がします :thinking:

2023-06-04 17:21 UTC, uki00a commented on docs/report/20.md
> +  - tizelStripe<!-- 聞き取れなかったので教えてほしいです -->もある
これはうろ覚えでなのでちょっと自身はないですが、たしかSlackの話だったような気がします :thinking:

2023-06-05 01:02 UTC, kt3k commented on docs/report/20.md
> +  - Google Developer Advocateの人が`setTimeout`などを並べ立てて「ハンドラ関数が第一引数になっているのはデザインの失敗である」とツイートしてた<!--このツイートのリンクが知りたいです-->
こちらです
https://twitter.com/jaffathecake/status/1646798390355697664

2023-06-05 01:04 UTC, kt3k commented on docs/report/20.md
> +  - deno compileとdeno 〇〇<!-- TODO: ここが聞き取れなかったです -->で`npm:`を使える道が拓ける
そこは単に deno deploy と言っていたはずと思います

2023-06-05 01:05 UTC, kt3k commented on docs/report/20.md
> +  - deno compileとdeno 〇〇<!-- TODO: ここが聞き取れなかったです -->で`npm:`を使える道が拓ける
ちなみにですが、deno compile はすでに `npm:` をサポートしてるらしくて、`deno compileと` の部分は間違いっぽいので、消してもらえると助かりますmm

2023-06-05 01:08 UTC, kt3k commented on docs/report/20.md
> +  - tizelStripe<!-- 聞き取れなかったので教えてほしいです -->もある
自分が挙げていたのは、[chizelstrike](https://github.com/chiselstrike/chiselstrike) ですね、slack も挙がっていましたね

2023-06-05 01:10 UTC, kt3k commented on docs/report/20.md
> +  <!-- TODO: Kintoneの人に尋ねた話、載せないほうが良ければ変えます -->
まあ、噂話レベルの内容なので、大丈夫かなと思います。

2023-06-05 01:11 UTC, kt3k commented on docs/report/20.md
> +### KVでatmicの中で関数が渡せると自由度が高まると思いますが、APIは拡張される見込みはありますか？
```suggestion
### KVでatomicの中で関数が渡せると自由度が高まると思いますが、APIは拡張される見込みはありますか？
```

2023-06-05 01:16 UTC, kt3k commented
一旦見終わりました!

2023-06-05 12:18 UTC, windchime-yk commented on docs/report/20.md
> +  - Google Developer Advocateの人が`setTimeout`などを並べ立てて「ハンドラ関数が第一引数になっているのはデザインの失敗である」とツイートしてた<!--このツイートのリンクが知りたいです-->
ありがとうございます！

2023-06-05 12:18 UTC, windchime-yk commented on docs/report/20.md
> +  - deno compileとdeno 〇〇<!-- TODO: ここが聞き取れなかったです -->で`npm:`を使える道が拓ける
なるほど承知です！ ご指摘ありがとうございますー！

2023-06-05 12:19 UTC, windchime-yk commented on docs/report/20.md
> +    - 〇〇<!-- ここを聞き逃しました -->が同じプロセスに同居しているので、別プロセスが建てられると攻撃に悪用されてしまうため
@kt3k @uki00a 
特にコメントなさそうなので、こちらについては以下を削除して対応しようと思います！
```
〇〇<!-- ここを聞き逃しました -->が同じプロセスに同居しているので、
```

2023-06-05 12:24 UTC, windchime-yk commented on docs/report/20.md
> +  - tizelStripe<!-- 聞き取れなかったので教えてほしいです -->もある
kt3kさんが挙げてらっしゃったものがなんだろうな、となってましたね。
教えていただきありがとうございますー！

2023-06-05 12:50 UTC, windchime-yk commented
@kt3k @uki00a 
修正が終わりましたので、再レビューよろしくお願いします！

2023-06-05 16:49 UTC, uki00a approved these changes
対応ありがとうございます！ :bow:

LGTM!!

2023-06-06 04:33 UTC, kt3k approved these changes
LGTM!

2023-06-06 13:20 UTC, merged