2023-08-18
deno-ja/denobata-monthly-report pull request #43
Opened 2023-08-18 09:42 UTC by windchime-yk

2023-08-24 00:30 UTC, windchime-yk commented
@kt3k @uki00a
遅くなりましたが、第22回のレポート作成しましたので、レビューをお願いしますー！

2023-08-24 07:20 UTC, kt3k commented on docs/report/22.md
> +- 一回[`deno_modules`でPR出した](https://github.com/denoland/deno/pull/19977)らコミュニティから異論があり[`vendor`に変更された](https://github.com/denoland/deno/pull/20065)
各 PR にリンクありがとうございます!

2023-08-24 08:32 UTC, kt3k commented on docs/report/22.md
> +- Deno.openKVの引数にプロジェクトのKVページにあるURLを指定して本番のKVをいじれる
```suggestion
- Deno.openKvの引数にプロジェクトのKVページにあるURLを指定して本番のKVをいじれる
```

2023-08-24 08:33 UTC, kt3k approved these changes
LGTM with nits

2023-08-24 12:45 UTC, uki00a requested changes
ありがとうございます！細かな箇所でコメントいたしましたが、全体的によさそうに見えます！ :bowing_man:

2023-08-24 12:45 UTC, uki00a commented on docs/report/22.md
> +- `defineRoute`は`req`とか`ctx`に自力で書かなくても良くなる
細かいですが、↓のようにすると少し意図がわかりやすくなりそうな気がしました
```suggestion
- `defineRoute`は`req`とか`ctx`に自力で引数の型を書かなくても良くなる
```

2023-08-24 12:45 UTC, uki00a commented on docs/report/22.md
> +- 非同期はこのほうが書きやすいが、同期だと従来の方法が書きやすい
こちらも同様です！
```suggestion
- 非同期ルートコンポーネントはこのほうが書きやすいが、同期だと従来の方法が書きやすい
```

2023-08-24 15:02 UTC, windchime-yk commented
レビューありがとうございます！
修正しましたので、 @uki00a さんから承認いただけたらマージしようと思います！

2023-08-24 19:09 UTC, uki00a approved these changes
LGTM!! :+1:

2023-08-25 00:21 UTC, windchime-yk commented
レビューありがとうございました！ マージいたします！

2023-08-25 00:22 UTC, merged