2023-11-17
deno-ja/denobata-monthly-report pull request #45
Opened 2023-11-16 15:14 UTC by windchime-yk

2023-11-19 13:20 UTC, windchime-yk reviewed
@kt3k @uki00a 
夜分遅くに失礼します！
第24回のレポートを作成したので、レビューをお願いいたしますー！

当日、通信環境が悪かったのか入り直したりしたので、抜け漏れや誤記載あるかと思います。
不明点はコメントで記載させていただきました。よろしくお願いします。

2023-11-19 13:20 UTC, windchime-yk commented on docs/report/24.md
> +- これがデフォルトになる？
聞き取りづらかったのですが、uki00aさんがこういったことを仰ってた記憶がありました。違ってたら教えてください……。

2023-11-19 13:20 UTC, windchime-yk commented on docs/report/24.md
> +- Freshで対応が入るかも
PRとIssueを見てみたのですが、それらしいものが見つからず教えていただきたいです 🙇 
以下のMarvinさんのコメントがそれっぽいかな？ と思ったのですが、確証は得られず……。
https://github.com/denoland/deno/pull/20876#issuecomment-1764808464

2023-11-19 13:20 UTC, windchime-yk commented on docs/report/24.md
> +- Node.jsモジュールの中にWASIモジュールを組み込むようにする話があったはず
Node.jsのWASI対応って確か以前からあったような？ と思っており、聞き間違えたと思うのでどういう話されてたか教えていただきたいです 🙇

2023-11-19 14:46 UTC, uki00a requested changes
まとめありがとうございます！！

細かな箇所で数点だけコメントしたため、お時間ある際に確認いただけますでしょうか :pray:

2023-11-19 14:46 UTC, uki00a commented on docs/report/24.md
> +- これがデフォルトになる？
これはあっています！ :ok_man: `package.json`がある際は将来的にこの挙動をデフォルトにすることが検討されているようです。

2023-11-19 14:46 UTC, uki00a commented on docs/report/24.md
> +- Freshで対応が入るかも
そのコメントであっています！ :+1: :ok_man:

2023-11-19 14:46 UTC, uki00a commented on docs/report/24.md
> +- `config.json`で指定した場合は入っていないものも検知する
うろ覚えですが、ここはたしか
```suggestion
- `--unstable-hmr=file1,file2,...`のように指定されたファイルはモジュールグラフに入っていなくても検知する (ただし、それらの変更時はプロセスが再起動される)
```
のような話だった気がします :thinking:

2023-11-19 14:46 UTC, uki00a commented on docs/report/24.md
> +- Freshのための最適化
念の為ですが、確証はないため`おそらく`を入れていただけると :bowing_man: :pray: 
```suggestion
- おそらく、Freshのための最適化
```

2023-11-19 14:46 UTC, uki00a commented on docs/report/24.md
> +- Node.jsモジュールの中にWASIモジュールを組み込むようにする話があったはず
これはたしか将来的にDeno本体に`node:wasi`が実装される可能性がありそうかもしれないので、そうなったらどちらにせよ`deno_std/wasi`はなくてもよさそう、というような話だった気がします :thinking:

2023-11-22 06:39 UTC, kt3k commented on docs/report/24.md
> +  - Prismaは`.prisma`というディレクトリからrequireしている
👍

2023-11-22 06:40 UTC, kt3k commented on docs/report/24.md
> +- これがデフォルトになる？
ですね、package.json がある場合のデフォルトのモードになる予定のようです

2023-11-22 06:42 UTC, kt3k commented on docs/report/24.md
> +- 大量に`interface`を書いてると、依存の中の依存でドキュメントされていない可能性がある
細かいですが、TS の `interface` キーワードに限った話ではないため、バッククオートなしにするかインターフェースのようにカタカナ表記にした方が良いかもしれません

2023-11-22 06:44 UTC, kt3k commented on docs/report/24.md
> +- `config.json`で指定した場合は入っていないものも検知する
ですね、例として config.json を挙げていただけで、hmr 用の config ファイルがあるというわけではなさそうですね

2023-11-22 06:44 UTC, kt3k commented on docs/report/24.md
> +    - `bun --hot`というものがある模様
おー、なるほど。追加調査ありがとうございます!

2023-11-22 07:09 UTC, kt3k commented on docs/report/24.md
> +  - Fetch APIのService Workerの実装の仕方が違い、[文字列を返すとレスポンス相当となる](https://twitter.com/yusukebe/status/1718835883095552308)
追加調査ありがとうございます!

2023-11-22 07:48 UTC, kt3k approved these changes
LGTM

2023-11-22 07:51 UTC, kt3k commented on docs/report/24.md
> +  - Deno Subhostingの料金表を見る限り50秒
```suggestion
  - Deno Subhostingの料金表を見る限り50ミリ秒
```

2023-11-22 07:51 UTC, kt3k commented on docs/report/24.md
> +  - Deno Subhostingの料金表を見る限り50秒
あと、実際の時間ではなく、CPU Time であることも併記していただけると嬉しいかもです

2023-11-22 07:52 UTC, kt3k commented on docs/report/24.md
> +- enqueueやcronは通常より緩い
こちら今調べていますが、ドキュメント上では見つけられなかったので、deploy チームに問い合わせています

2023-11-22 07:59 UTC, kt3k commented on docs/report/24.md
> +- enqueueやcronは通常より緩い
聞いてみたところ CPU Time 50ミリ秒制限は cron と queue listener には適用されていないそうです。

非同期処理を挟まずに同期的に2秒以上処理し続ける (event loop を2秒以上止める) と kill されるようですが、それ以外の制限はかかっていないそうです (この仕様自体は多分暫定だと思うので、どういう制限を入れるかは検討中という表現が正しそうな気がします)

2023-11-22 07:59 UTC, kt3k approved these changes
LGTM

2023-11-22 13:11 UTC, windchime-yk commented on docs/report/24.md
> +- これがデフォルトになる？
ありがとうございますー！ ではこのままで！

2023-11-22 13:14 UTC, windchime-yk commented on docs/report/24.md
> +- Freshで対応が入るかも
ご確認ありがとうございます！ こちらのコメントリンクを本文に追加します！ 🙌

2023-11-22 13:18 UTC, windchime-yk commented on docs/report/24.md
> +- `config.json`で指定した場合は入っていないものも検知する
なるほど、公式マニュアル上にそれらしい記述がなかったのはそういうことだったんですね……。
訂正ありがとうございます！

2023-11-22 13:19 UTC, windchime-yk commented on docs/report/24.md
> +- Freshのための最適化
失礼しました、加筆ありがとうございます 🙇

2023-11-22 13:33 UTC, windchime-yk commented on docs/report/24.md
> +- 大量に`interface`を書いてると、依存の中の依存でドキュメントされていない可能性がある
ホントですね、失礼しました。
カタカナ表記に修正しようと思います！ ご指摘ありがとうございます！

2023-11-22 13:37 UTC, windchime-yk commented on docs/report/24.md
> +  - Deno Subhostingの料金表を見る限り50秒
あー！ ミリ抜けてましたすみません！ すごく遅くなってしまってましたね……。
CPUタイムについても承知です！ 併記しておきます！

2023-11-22 14:06 UTC, windchime-yk commented on docs/report/24.md
> +- enqueueやcronは通常より緩い
問い合わせありがとうございます！ 🙇 

- CPU Time 50ミリ秒制限は cron と queue listener には適用されていないらしい
- 非同期処理を挟まずに同期的に2秒以上処理し続ける (event loop を2秒以上止める) と kill される
  - それ以外の制限はかかっていないらしい
  - 仕様自体はおそらく暫定
  - どういう制限を入れるかは検討中

という内容で追加しようと思います！

2023-11-22 14:52 UTC, windchime-yk commented on docs/report/24.md
> +- Node.jsモジュールの中にWASIモジュールを組み込むようにする話があったはず
お、なるほどありがとうございますー！

2023-11-22 15:06 UTC, windchime-yk commented
@kt3k @uki00a 
レビューありがとうございました！
修正しましたので、再度のレビューをお願い致します！ 🙇

2023-11-23 02:53 UTC, kt3k commented on docs/report/24.md
> +  - 使用自体はおそらく暫定
```suggestion
  - 仕様自体はおそらく暫定
```

2023-11-23 02:53 UTC, kt3k approved these changes
LGTM 👍

2023-11-23 12:34 UTC, windchime-yk commented
レビューありがとうございました！ 誤字修正もありがとうございます！ 🙇 
マージさせていただきますー！

2023-11-23 12:35 UTC, merged